### ISSUE TITLE
Errors encountered at yarn start

### ISSUE THREAD

**Issue by lunchboxer** [graphql-boilerplates/react-fullstack-graphql#127]
I tried to follow the directions from the README and when I got to yarn start I got the following:
```
$ yarn start
yarn run v1.3.2
warning package.json: No license field
$ graphcool deploy && node src/index.js
? Please choose the cluster you want to deploy to 

local
You chose the cluster local, but don't have docker initialized, yet.
Please run $ graphcool local up to get a local Graphcool cluster.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
No problem! ...
```
$ graphcool local up
 ▸    local up is not a graphcool command.
 ▸    Perhaps you meant local upgrade
 ▸    Run graphcool help local for a list of available commands.

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ export DEBUG="*"

```
Wait what?
that's graphql-cli 2.9.4
graphcool 1.0.0-beta3.3.1

**Comment by marktani** [comment]
Hey @lunchboxer, it's `graphcool local start` instead of `graphcool local up`. The instructions are wrong, which is fixed here and released in `beta4`: https://github.com/graphcool/framework/issues/1471).

Let me know if that gets you going!

**Comment by lunchboxer** [comment]
Unfortunately it doesn't. graphcool local start works fine, but I shouldn't be seeing the first error. I can run graphcool local start and graphcool deploy and they work fine, but then yarn start still leads to the above result

**Comment by lunchboxer** [comment]
For what it's worth, I have tried a few other graphql-boilerplates today and none of them had this behavior.

**Comment by marktani** [comment]
Thanks, I'll look into this, it sounds like a version mismatch in this repo!
For now, you can go ahead and replace the `server` directory here with a server boilerplate 🙂

**Comment by lunchboxer** [comment]
that works. Thanks

**Comment by marktani** [comment]
I rehauled the boilerplate, it should work again.
