### ISSUE TITLE
devDependency for prisma missing

### ISSUE THREAD

**Issue by kbrandwijk** [graphql-boilerplates/react-fullstack-graphql#157]
The `package.json` does not include the devDependency for `prisma`, however the instructions mention that it is installed, and you can run `yarn prisma ...`.

**Comment by nikolasburk** [comment]
`prisma` was already listed under `devDependencies` - however it wasn't added as a _script_ yet. Just fixed that, thanks Kim 👍

**Comment by kbrandwijk** [comment]
Am I missing something? https://github.com/graphql-boilerplates/react-fullstack-graphql/blob/master/basic/package.json#L5-L8

**Comment by kbrandwijk** [comment]
Update: yes I was, there is a server subfolder in this repo. Sorry...
