### ISSUE TITLE
Missing in tutorial

### ISSUE THREAD

**Issue by lajlev** [graphql-boilerplates/react-fullstack-graphql#16]
You should mention that *Yarn* is required

**Comment by marktani** [comment]
Hey @lajlev! Which tutorial are you referring to? You should be able to use `npm` whereever` npm` is stated, as well/

**Comment by kbrandwijk** [comment]
Probably in the readme. However, there is a difference between yarn and npm, making yarn the better option on Windows (otherwise node-gyp will fail build on some architectures, yarn just skips the dependency on fs-events because it's optional). So please stick to yarn.

**Comment by marktani** [comment]
This issue is outdated. Please open a new issue if you have any problems or questions.
