### ISSUE TITLE
Infinite Scroll with FlatList for react native

### ISSUE THREAD

**Issue by michaelspeed** [graphql-boilerplates/react-fullstack-graphql#19]
I am trying to do infinite scroll with graphcool and flat list for react native. an example would be nice

**Comment by jhalborg** [comment]
Which GQL client are you using? In either case, look into using the onEndReached handle of Flatlist to trigger a fetch of more items. You can adjust the threshold with onEndReachedThreshold. Docs are here: https://facebook.github.io/react-native/docs/flatlist.html#onendreached

In the callback function, use your GQL client to append the list data. If you're still in doubt, I suggest reading up on standard pagination

**Comment by marktani** [comment]
This issue is outdated. Please open a new issue if you have any problems or questions.
