### ISSUE TITLE
Is the typescript version available?

### ISSUE THREAD

**Issue by muhajirframe** [graphql-boilerplates/react-fullstack-graphql#209]

**Comment by DevanB** [comment]
Do you mean for the client or server side portion of this boilerplate?

**Comment by iamclaytonray** [comment]
@DevanB @muhajirframe - I can write a fullstack TS boilerplate in a few days, if either of you want

**Comment by DevanB** [comment]
I’m not sure we want to build a TS version of the boilerplates, yet. That opens up a can of worms of then building a Flow, Reason, etc version. My question was if @muhajirframe wanted a TS version of the server in the React boilerplates, or wanted a TS version of the entire project.

**Comment by iamclaytonray** [comment]
Welp, if you want me to build a TS version (or Reason), I'm definitely down to do one 👍

**Comment by muhajirframe** [comment]
I mean the boilerplate, It would be nice of have a starter. So we can use it without configuring it at first.

**Comment by DevanB** [comment]
@muhajirframe right now that isn’t on our roadmap. However, if you’d like to contribute back a TypeScript React advances boilerplate, we would love to accept it!

**Comment by muhajirframe** [comment]
@DevanB I am not so good with configuring typescript yet. But I'll try it though. I'll see if I can contribute :)

 @iamclaytonray Yeah that would be amazing to have typescript and reason :+1:

**Comment by iamclaytonray** [comment]
@DevanB - Are you fine with that? I can write a minimal boilerplate for both TypeScript & Reason to at least give others somewhere to start without spending an hour or two (or more) with configuration

**Comment by iamclaytonray** [comment]
(I'd be able to maintain as well. Maybe not resolve issues every day but after work, spend about an hour here and there)

**Comment by DevanB** [comment]
Okay, so we have a ReasonML repo setup. Please go ahead and open a PR for a BP and we will get it all rolling! 😃

As for the TS, feel free to fork and start developing. I’m going to open up a conversation in the contributors channel on Slack.

**Comment by iamclaytonray** [comment]
BP === Boilerplate? For Reason, are we doing a simple & advanced or how are we going about that?

**Comment by DevanB** [comment]
Sorry, yes! BP is boilerplate :) We will do the same minimal, basic, and advanced structure.

**Comment by iamclaytonray** [comment]
@DevanB - Just got hit by another wave of contracts - will have to postpone this unless someone else wants to take my place. Sorry dude

**Comment by DevanB** [comment]
Totally understandable. 

I will, however, close this issue since we have discussed and come to a conclusion.
