### ISSUE TITLE
Can get rid of http-link if and use web sockets instead

### ISSUE THREAD

**Issue by manjula91** [graphql-boilerplates/react-fullstack-graphql#235]
There will be no overhead of http connections

```
import React, { Component } from "react";
import "./App.css";
import { ApolloClient } from "apollo-client";
import { InMemoryCache } from "apollo-cache-inmemory";
import { ApolloProvider } from "react-apollo";
import App from "./App";
import { SubscriptionClient } from "subscriptions-transport-ws";
import { WebSocketLink } from "apollo-link-ws";

const wsClient = new SubscriptionClient("ws://localhost:8000/subscriptions", {
  reconnect: true
});

// Create a WebSocket link:
const wsLink = new WebSocketLink(wsClient);

const client = new ApolloClient({
  link: wsLink,
  cache: new InMemoryCache()
});

class App extends Component {
  render() {
    return (
      <ApolloProvider client={client}>
        <App />
      </ApolloProvider>
    );
  }
}

export default App;

```

**Comment by iamclaytonray** [comment]
That's assuming that everyone will use websockets for every "endpoint". You can add a websocket link, along with other links (auth & http) to ApolloClient.

**Comment by manjula91** [comment]
@iamclaytonray yes thats an assumption though. 
You can add a websocket link, along with other links (auth & http) to ApolloClient.
```Yes I know that. But web socket connection seem to be faster ```

**Comment by iamclaytonray** [comment]
I think you misunderstood me. If you remove a standard http link and only have a websocket link on the client, the client will only take data from a websocket. That forces you to only use websockets. It's not an assumption. The assumption I was referring to was that everyone would use websockets for their entire application, which may seem faster, but puts additional load on servers. Even in Lambda/Azure/etc, this is not ideal. You only want to bring live data for a few things in an app

**Comment by manjula91** [comment]
Gotcha :) I misunderstood ;)

**Comment by stubailo** [comment]
Hi, thanks for the suggestion but we definitely recommend using HTTP when possible, since it's easier to scale out!
