### ISSUE TITLE
Update server directory 

### ISSUE THREAD

**Issue by marktani** [graphql-boilerplates/react-fullstack-graphql#247]
It uses an old install script and old dependencies, amongst other things.

The code from node-graphql should be transferred to the server directory of minimal and basic.

**Comment by manjula91** [comment]
Cool @marktani This is for basic right?

**Comment by manjula91** [comment]
@marktani I check the react boilerplate The problem seemed only with the basic install script. Rest all seems fine :)

**Comment by marktani** [comment]
Thanks so much! 🙌 Yup, closing this :)
