### ISSUE TITLE
Use best practices for authentication

### ISSUE THREAD

**Issue by kbrandwijk** [graphql-boilerplates/react-fullstack-graphql#26]
The current Auth0-react examples leave a lot to be desired for solid authentication. This example: https://auth0.com/blog/reactjs-authentication-tutorial/ follows a better approach. If that approach can be adopted, then these examples can be a real boilerplate for a new app.

**Comment by marktani** [comment]
This issue is outdated. Please open a new issue if you have any problems or questions.
