### ISSUE TITLE
update quickstart-with-apollo to RR4

### ISSUE THREAD

**Issue by marktani** [graphql-boilerplates/react-fullstack-graphql#33]
apparently the current code only works with RR3.

**Comment by stevensacks** [comment]
https://facebook.github.io/relay/docs/routing.html

As per Relay Modern docs, you should not use React Router 4.

> The component-based approach of React Router v4 does not readily allow for aggregating the data requirements for nested routes, and as such does not readily permit an approach that will avoid request waterfalls from nesting QueryRenderer components.

**Comment by stevensacks** [comment]
They recommend Found-Relay instead:

https://github.com/4Catalyzer/found-relay
