### ISSUE TITLE
Confusing "getting started" instructions

### ISSUE THREAD

**Issue by rojobuffalo** [graphql-boilerplates/react-fullstack-graphql#369]
Could we maybe have a 1, 2, 3, ... in the README for how to start a project using one of these boilerplates? Do you clone this repo first, or just a copy of `/minimal`, `/basic`, or `/advanced`? Are  you supposed to install `graphql-cli` and then do `graphql create`?

Based on the README, it says go to the chosen boilerplate README. I look at `minimal/README` and there is nothing in the section called "Getting Started". I assume step 1 is copy that directory and run `npm i`. It says

> yarn start or npm run start starts GraphQL server on http://localhost:4000

But `npm run start` fires up localhost:3000, there is no service running for me on port 4000. The browser just says "an unexpected error occurred" and there is no response from port 4000. Are there instructions somewhere that I am missing?

**Comment by rojobuffalo** [comment]
I have it working but the instructions need some work.

1. Clone the repo:
```bash
git clone git@github.com:graphql-boilerplates/react-fullstack-graphql.git
```

2. Change into the directory and move your chosen boilerplate to make your new project root:
```bash
cd react-fullstack-graphql
mv minimal ../your-new-project
```

3. Install the server and the frontend app:
```bash
npm i
cd server && npm i
```

4. Run the server:
```bash
cd server
npm run start
```

5. Open a new terminal tab, move to project root, and run the frontend app:
```bash
cd ..
npm run start
```

**Comment by vivek12345** [comment]
@rojobuffalo See if these changes would help you better.
https://github.com/graphql-boilerplates/react-fullstack-graphql/pull/408

**Comment by rojobuffalo** [comment]
Looks good :+1:
