### ISSUE TITLE
Unexpected token (

### ISSUE THREAD

**Issue by TheoMer** [graphql-boilerplates/react-fullstack-graphql#393]
OS: Windows 1 Pro Build 17115.rs4_release.180302-1642
Node: 6.10.2
Yarn: 1.7.0
graphql-cli: 2.16.3

Ok, so running:

```
graphql create react-fullstack-graphql --boilerplate react-fullstack-advanced
```

generates the above mentioned error message (See image), and fails the installation process at that point. What is the issue here?

![install-error](https://user-images.githubusercontent.com/15969262/41605096-9c6f20d4-73d8-11e8-8365-435695bb50bd.jpg)

**Comment by niteshp27** [comment]
Same here, generates the below error message refer image
![image](https://user-images.githubusercontent.com/907553/41641529-1d36e80a-7483-11e8-9916-ce65e5d60a44.png)

**Comment by manjula91** [comment]
@marktani can you assign this to me

**Comment by TheoMer** [comment]
@marktani @manjula91 May I ask whether there's an eta as to the resolution of this issue?

**Comment by manjula91** [comment]
@TheoMer will look into the issue this week. It should be done by end of this week.

Regards
Manjula

**Comment by bristoljon** [comment]
I'm hitting unexpected token on `npm start` of `/server`. It seems there is a spread operator at line 47 but the js is not transpiled. Not sure if this is same issue, if not I'll make a separate one..

```
jon@jon-nuc:~/dev/my-app/server$ npm start

> my-app@ start /home/jon/my-app/server
> node src/index.js

/home/jon/hello-world/my-app/server/src/index.js:47
    ...req,
    ^^^


SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```
I'm on Ubuntu

**Comment by bristoljon** [comment]
Ah sorry, my fault I was running node v8.2.1. Upgrading to v8.11.3 fixes this

**Comment by vivek12345** [comment]
@TheoMer This issue is a node issue. For now the boilerplates don't work well on an older node version.Can you try to update your node version to >=8 and try to create the project.

It would solve the issue for you.

Let me know if you are facing issue even with node 8

**Comment by TheoMer** [comment]
@vivek12345 Thank you so much. Updating my version of nodejs to 8.11.3  resolved the issue.
