### ISSUE TITLE
authentication-with-email example contains schema issue

### ISSUE THREAD

**Issue by gstvbrg** [graphql-boilerplates/react-fullstack-graphql#42]
Hey whats up! It seems like https://github.com/graphcool-examples/react-graphql/commit/563004c276928013722cdeecf84173985374f782 doesn't fully address related issue #21 and commit 8413895da7644f809edf96ef81dea5eed5ed0aa3. While the updated readme does remove the 'email' field, which is preventing the email auth provider from properly enabling, the given schema at https://graphqlbin.com/insta-email.graphql still contains the troublesome 'email' field

**Comment by marktani** [comment]
This issue is outdated. Please open a new issue if you have any problems or questions.
