### ISSUE TITLE
can't run `graphcool init graphcool --template blank`

### ISSUE THREAD

**Issue by lifeiscontent** [graphql-boilerplates/react-fullstack-graphql#46]
I get this error

Error: The following option is not recognized: template
Use `graphcool init --help` to see a list of all possible options.

$ graphcool version
1.3.7

**Comment by peterj** [comment]
I've noticed this as well (also, the ```modules``` subcommand is missing). Looks like all this is available in the next version. Try installing it like this: 

```
npm install -g graphcool@next
```

**Comment by ylac** [comment]
I had to use:

`npm install -g graphcool@1.3.7`

to get it to work.

**Comment by cipriancaba** [comment]
1.3.7 doesn't work.. try `npm install -graphcool@1.4.0`

**Comment by iamclaytonray** [comment]
Try `npm install -g graphcool@alpha` and then...

`cd Desktop`
`mkdir demo && cd demo`
`graphcool init`
`graphcool add-template mailgun`

**Comment by marktani** [comment]
This issue is outdated. Please open a new issue if you have any problems or questions.
