### ISSUE TITLE
`Enum value 'createdAt_DESC' is undefined` for `react-apollo-instagram-example`

### ISSUE THREAD

**Issue by dstotijn** [graphql-boilerplates/react-fullstack-graphql#51]
After doing the (awesome) onboarding tutorial on the Web Console and running the (autogenerated) `react-apollo-instagram-example` app, I got this error on the `ListPage` route:

```
Unhandled (in react-apollo) Error: GraphQL error: Argument 'orderBy' expected type 'PostOrderBy' but got: createdAt_DESC. Reason: Enum value 'createdAt_DESC' is undefined in enum type 'PostOrderBy'. Known values are: description_ASC, description_DESC, id_ASC, id_DESC, imageUrl_ASC, imageUrl_DESC. (line 2, column 21):
  allPosts(orderBy: createdAt_DESC) {
```

Not sure if I missed something during setting up the project. The field `createdAt` is predefined and hidden in the schema, so it should exist I think 🤔

**Comment by marktani** [comment]
This issue is outdated. Please open a new issue if you have any problems or questions.
