### ISSUE TITLE
Issue: You are referencing a node that does not exist.

### ISSUE THREAD

**Issue by alan345** [graphql-boilerplates/react-fullstack-graphql#53]
Hi !
Thanks for all examples! Very Useful!
I have installed 10 days agoo example: https://github.com/graphcool-examples/react-graphql/tree/master/subscriptions-with-apollo-worldchat it was working fine. 
Today, I try to install it again, and I get this issue: 

![image](https://user-images.githubusercontent.com/15246526/31865682-ebf308dc-b772-11e7-825f-5e696d5f4c99.png)
`You are referencing a node that does not exist. Please check your mutation to make sure you are only creating edges between existing nodes. Id if available: cj90ba3com5hd013965pytw2t`

 I used Graphcool CLI with `npm install -g graphcool@next`
Thanks for your help

**Comment by iamclaytonray** [comment]
It looks like you are trying to add a connection between two nodes with at least one incorrect ID.

**Comment by marktani** [comment]
This issue is outdated. Please open a new issue if you have any problems or questions.
