### ISSUE TITLE
tutorial code doesn't match with code linked to it.

### ISSUE THREAD

**Issue by topaztee** [graphql-boilerplates/react-fullstack-graphql#65]
The [creatuser.js](https://github.com/graphcool-examples/react-graphql/blob/master/authentication-with-email-and-apollo/src/components/CreateUser.js) code on github  doesnt match with the[ tutorials code ](https://www.graph.cool/docs/tutorials/auth/authentication-with-email-and-password-for-react-and-apollo-cu3jah9ech#setting-up-your-graphql-server)

**Comment by marktani** [comment]
This issue is outdated. Please open a new issue if you have any problems or questions.
