### ISSUE TITLE
subscriptions-with-apollo-worldchat example is broken ?

### ISSUE THREAD

**Issue by vunguyenhung** [graphql-boilerplates/react-fullstack-graphql#66]
I've cloned the repository and run subscriptions-with-apollo-worldchat example with a Graphcool testing server (you can test it with serviceID: `cjatez8yz0ru30140145a694b`). 
### Reproduce error:
- After cloning the project, I created a Graphcool server and had it running with serviceID: `cjatez8yz0ru30140145a694b`
- Then I added it to `serviceID` of `src/components/App.js`
- Install dependencies with `npm install`, then start with `npm start`.
- The first error I received when running the project is about missing `subscription-transport-ws` dependency which is used by `apollo-link-ws`. I installed it and the error disappears.
- The second error was when the application is running, in the console there was an warning: `WebSocket connection to 'wss://subscriptions.graph.cool/v1/cjatez8yz0ru30140145a694b' failed: WebSocket is closed before the connection is established.`
- I used the application to save a new message to the server, it works, but the subscription was broken. And the mutation things were broken as well when I refreshed the page.

**Comment by marktani** [comment]
This issue is outdated. Please open a new issue if you have any problems or questions.
