### ISSUE TITLE
Error when run Yarn

### ISSUE THREAD

**Issue by luckyman69** [graphql-boilerplates/react-fullstack-graphql#67]
I have error 
"yarn run v1.3.2
error Command "start" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command."
Please help me!

**Comment by vladbesson** [comment]
+1

**Comment by vladbesson** [comment]
I checked `react-graphql/quickstart-with-apollo/package.json` and found that it is empty, so I just grabbed this https://github.com/graphcool-examples/react-graphql/blob/master/quickstart-with-apollo/package.json and now it is working

**Comment by marktani** [comment]
This issue is outdated. Please open a new issue if you have problems.
