### ISSUE TITLE
TypeError: Cannot read property 'loading' of undefined

### ISSUE THREAD

**Issue by vonwao** [graphql-boilerplates/react-fullstack-graphql#68]
In authentication-with-email-and-apollo:

<img width="803" alt="screenshot 2017-12-14 09 19 44" src="https://user-images.githubusercontent.com/377000/34005614-5259b27c-e0b0-11e7-99ee-f342a6159831.png">

**Comment by marktani** [comment]
This issue is outdated. Please open a new issue if you have problems.
